# Metadata for the local development cluster.
apiVersion: kube-state/v1
kind: Cluster
metadata:
  name: local
spec:
  # Local Kubernetes distribution used for development.
  distribution: kind
  kubernetesVersion: "1.30"
  releases:
    - name: cnpg
      namespace: cnpg-system
    - name: redis-operator
      namespace: redis-operator
    - name: shop-operator
      namespace: shop-operator-system
    - name: shophub
      namespace: shophub
    - name: shophub-discord
      namespace: observability
    - name: loki
      namespace: observability
    - name: alloy
      namespace: observability
    - name: ingress-nginx
      namespace: ingress-nginx
    - name: kube-prometheus-stack
      namespace: observability
